version: "3.9"

services:
  api:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./storage:/app/storage

  worker:
    build: .
    command: celery -A app.workers.celery_app worker -l info -Q items,requests,email
    env_file: .env
    depends_on:
      - postgres
      - redis
    volumes:
      - ./storage:/app/storage

  beat:
    build: .
    command: celery -A app.workers.celery_app beat -l info
    env_file: .env
    depends_on:
      - postgres
      - redis

  flower:
    build: .
    command: celery -A app.workers.celery_app flower --port=5555
    env_file: .env
    ports:
      - "5555:5555"
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: quotebot
      POSTGRES_PASSWORD: quotebot
      POSTGRES_DB: quotebot
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - "6380:6379"
    restart: unless-stopped

volumes:
  pgdata: