"""initial

Revision ID: 45f8198bd2b3
Revises: 
Create Date: 2026-06-10 06:34:39.633934
"""

from alembic import op
import sqlalchemy as sa


revision = '45f8198bd2b3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=True),
    sa.Column('item_id', sa.String(length=36), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_logs_item_id'), 'llm_logs', ['item_id'], unique=False)
    op.create_index(op.f('ix_llm_logs_request_id'), 'llm_logs', ['request_id'], unique=False)
    op.create_table('quote_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.Enum('EMAIL', 'UPLOAD', name='requestsource'), nullable=False),
    sa.Column('status', sa.Enum('RECEIVED', 'PARSING', 'PARSE_ERROR', 'SEARCHING', 'COMPLETED', 'FAILED', name='requeststatus'), nullable=False),
    sa.Column('email_message_id', sa.String(length=255), nullable=True),
    sa.Column('email_thread_id', sa.String(length=255), nullable=True),
    sa.Column('reply_to', sa.String(length=255), nullable=True),
    sa.Column('document_hash', sa.String(length=64), nullable=True),
    sa.Column('raw_document_path', sa.String(length=512), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('parse_method', sa.Enum('TEMPLATE_XLSX', 'TEMPLATE_CSV', 'EMAIL_TABLE', 'LLM_FALLBACK', name='parsemethod'), nullable=False),
    sa.Column('report_path', sa.String(length=512), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_message_id')
    )
    op.create_index(op.f('ix_quote_requests_document_hash'), 'quote_requests', ['document_hash'], unique=False)
    op.create_index(op.f('ix_quote_requests_status'), 'quote_requests', ['status'], unique=False)
    op.create_table('quote_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('preferred_brand', sa.String(length=255), nullable=True),
    sa.Column('specs', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SEARCHING', 'COMPLETED', 'FAILED', 'PARTIAL', 'NO_RESULTS', name='itemstatus'), nullable=False),
    sa.Column('searches_used', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['quote_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quote_items_request_id'), 'quote_items', ['request_id'], unique=False)
    op.create_index(op.f('ix_quote_items_status'), 'quote_items', ['status'], unique=False)
    op.create_table('item_options',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('tier', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=1024), nullable=False),
    sa.Column('seller', sa.String(length=512), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('price_amount', sa.Float(), nullable=False),
    sa.Column('price_currency', sa.String(length=8), nullable=False),
    sa.Column('price_usd', sa.Float(), nullable=False),
    sa.Column('equivalence_score', sa.Float(), nullable=False),
    sa.Column('equivalence_level', sa.String(length=16), nullable=False),
    sa.Column('equivalence_reason', sa.Text(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['quote_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_options_item_id'), 'item_options', ['item_id'], unique=False)
    op.create_table('search_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('tier', sa.String(length=16), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('query', sa.String(length=1024), nullable=False),
    sa.Column('iteration', sa.Integer(), nullable=False),
    sa.Column('results_count', sa.Integer(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['quote_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_logs_item_id'), 'search_logs', ['item_id'], unique=False)
    # ### end Alembic commands ### 


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_search_logs_item_id'), table_name='search_logs')
    op.drop_table('search_logs')
    op.drop_index(op.f('ix_item_options_item_id'), table_name='item_options')
    op.drop_table('item_options')
    op.drop_index(op.f('ix_quote_items_status'), table_name='quote_items')
    op.drop_index(op.f('ix_quote_items_request_id'), table_name='quote_items')
    op.drop_table('quote_items')
    op.drop_index(op.f('ix_quote_requests_status'), table_name='quote_requests')
    op.drop_index(op.f('ix_quote_requests_document_hash'), table_name='quote_requests')
    op.drop_table('quote_requests')
    op.drop_index(op.f('ix_llm_logs_request_id'), table_name='llm_logs')
    op.drop_index(op.f('ix_llm_logs_item_id'), table_name='llm_logs')
    op.drop_table('llm_logs')
    # ### end Alembic commands ###